3_IvanaStojkovska/3_IvanaStojkovska/Controllers/LinksController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using _3_IvanaStojkovska.Models;

namespace _3_IvanaStojkovska.Controllers
{
    public class LinksController : Controller
    {
        private IvanaStojkovskaContext db = new IvanaStojkovskaContext();

        // GET: Links

        public ActionResult Index()
        {
            return View(db.Links.ToList());
        }

        public ActionResult AllLinks()
        {
            return View(db.Links.ToList());
        }
        // GET: Links/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = db.Links.Find(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // GET: Links/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Links/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,LinkUrl,Title,Description")] Link link)
        {
            if (ModelState.IsValid)
            {
                db.Links.Add(link);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(link);
        }

        // GET: Links/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = db.Links.Find(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // POST: Links/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,LinkUrl,Title,Description")] Link link)
        {
            if (ModelState.IsValid)
            {
                db.Entry(link).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(link);
        }

        // GET: Links/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Link link = db.Links.Find(id);
            if (link == null)
            {
                return HttpNotFound();
            }
            return View(link);
        }

        // POST: Links/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Link link = db.Links.Find(id);
            db.Links.Remove(link);
            db.SaveChanges();
            return RedirectToAction("Index");
        }


        public ActionResult LinksList(string name)
        {
            var links = db.Links;

            if (!string.IsNullOrWhiteSpace(name))
            {
                var filteredResult =
                    db.Links
                    .Where(x =>
                                x.Title.Contains(name)
                            )
                    .ToList();

                return View(filteredResult);
            }
            return View(links.ToList());
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

3_IvanaStojkovska/3_IvanaStojkovska/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - LinkApplication </title>
    <link href="~/Content/Site.css" rel="stylesheet" type="text/css" />
    <link href="~/Content/bootstrap.min.css" rel="stylesheet" type="text/css" />
    <script src="~/Scripts/modernizr-2.6.2.js"></script>
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

            </div>
            <div class="collapse navbar-collapse MyMenu" id="bs-example-navbar-collapse-1">
                <ul class="nav navbar-nav navbar-right">
                    <li class="page-scroll">
                        <a href="@Url.Action("LinksList", "Links")">Home</a>
                    </li>
                    <li class="page-scroll">
                        <a href="@Url.Action("Register", "Account")">Register</a>
                    </li>
                    <li class="page-scroll">
                        <a href="@Url.Action("Login", "Account")">Sign In</a>
                    </li>
                </ul>
            </div>
        </div>
    </div>

    <div class="container body-content">
        @Html.Partial("_LoginPartial")
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - Link Application</p>
        </footer>
    </div>

    <script src="~/Scripts/jquery-1.10.2.min.js"></script>
    <script src="~/Scripts/bootstrap.min.js"></script>
</body>
</html>

3_IvanaStojkovska/3_IvanaStojkovska/Views/Shared/_UserNavigation.cshtml
<ul class="nav nav-tabs">
    <li role="presentation">@Html.ActionLink("Index", "Index", "Links")</li>
    <li role="presentation">@Html.ActionLink("Create a link", "Create", "Links")</li>
</ul>